title: Johan Obando-Ceron
description: DPhil/PhD Student @ Mila, QueÃÅbec AI Institute and the University of Montreal.
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
theme: jekyll-theme-cayman

# Icons in the footer for contacting
social-network-links:
  # email: "joe@bloggs.com"
#  facebook: 
  github: johanobandoc
  google-scholar: KViAb3EAAAAJ
  twitter: johanobandoc
#  reddit: yourname
#  google-plus: +DeanAttali
  linkedin: johan-obando
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
  instagram: johanobandoc
  youtube: johanobandoc
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
